language: objective-c
osx_image: xcode63
xcode_workspace: AeroGearSyncClient.xcworkspace
xcode_scheme: AeroGearSyncClient
xcode_sdk: iphonesimulator

before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master